.install_base:
  extends: .base-job
  services: []
  stage: Install
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always

.install_lib:
  extends:
    - .install_base
    - .feature-job
  script:
    - composer install

install:lib:
  extends: .install_lib
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - vendor/

# Update `install` cache when committing to develop.
.only_if_develop:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

install:lib:update-cache:
  extends:
    - .install_lib
    - .only_if_develop
  cache:
    key:
      files:
        - composer.json
      prefix: install:lib
    paths:
      - vendor
    policy: pull-push
