# Use include:template to include .gitlab-ci.yml templates that are shipped with GitLab.
# These files is referenced as it is regularly updated by Gitlab

# https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Security/SAST.gitlab-ci.yml
# https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#configuration

# NOTE: SAST jobs only suppport 1 project folder?
# https://gitlab.com/gitlab-org/gitlab/-/issues/228861

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

# Gitlab SAST Scanning Overrides
sast:
  stage: SAST
  allow_failure: false

.job-template-scanner-base:
  interruptible: true
  needs: []

# nodejs-scan-sast:
#   extends:
#     - .sast-analyzer
#     - .job-template-scanner-base
#   rules:
#     - if: $SAST_DISABLED
#       when: never
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       when: always

# eslint-sast:
#   extends:
#     - .sast-analyzer
#     - .job-template-scanner-base
#   rules:
#     - if: $SAST_DISABLED
#       when: never
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       when: always

# semgrep-sast:
#   extends:
#     - .sast-analyzer
#     - .job-template-scanner-base
#   rules:
#     - if: $SAST_DISABLED
#       when: never
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       exists:
#         - '**/*.js'
#         # - '**/*.jsx'
#         - '**/*.ts'
#         - '**/*.tsx'

### Gitlab Dependency Scanning Overrides
dependency_scanning:
  stage: SAST

# Retire JS only supports scanning the first found yarn.lock file,
# AKA /api is scanned, but /ui is not.
# retire-js-dependency_scanning:
#   extends:
#     - .ds-analyzer
#     - .job-template-scanner-base
#   rules:
#     - if: $DEPENDENCY_SCANNING_DISABLED
#       when: never
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       when: always
#   before_script:
#     - cp api/.npmrc-default api/.npmrc

# gemnasium-dependency_scanning:
#   extends:
#     - .ds-analyzer
#     - .job-template-scanner-base
#   rules:
#     - if: $DEPENDENCY_SCANNING_DISABLED
#       when: never
#     - if: $CI_MERGE_REQUEST_IID
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#       when: always
#   before_script:
#     - cp api/.npmrc-default api/.npmrc
#   artifacts:
#     paths:
#       - gl-dependency-scanning-report.json
#     expire_in: 1 day
