# Script Helpers

.script_aws_login: &script_aws_login
  # TODO: new login command from voltaire, try using.
  # - aws ecr get-login-password | docker login --username AWS --password-stdin 434875166128.dkr.ecr.us-east-1.amazonaws.com
  - $(aws ecr get-login --region ${AWS_REGION} --no-include-email)

.script_gitlab_login: &script_gitlab_login
  - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}

.job-base-tests:
  stage: Test
  extends:
    - .base-job
    - .feature-job
  variables:
    AWS_ACCESS_KEY_ID: ${DEVELOP_AWS_ACCESS_KEY_ID_CD}
    AWS_SECRET_ACCESS_KEY: ${DEVELOP_AWS_SECRET_ACCESS_KEY_CD}
  before_script:
    - mkdir -p -m 777 logs
    - mkdir -p -m 777 ${TEST_SUITE_ARTIFACTS_FOLDER}
    - *script_aws_login
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit: ['./junit-report.xml']
      cobertura: ['./cobertura-report.xml']
  tags:
    - msts-caasdevx-test-runner

###### LINTING
.job-linting:
  extends: .job-base-tests
  needs:
    - install:lib
  variables:
    TEST_CONTAINER_NAME: lib-lint
    TEST_SUITE_ARTIFACTS_FOLDER: logs
  script:
    - composer lint

Library Linting:
  extends:
    - .job-linting

###### LIBRARY TESTS
.job-lib-tests:
  extends: .job-base-tests
  needs:
    - install:lib
  variables:
    TEST_CONTAINER_NAME: lib-tests
    TEST_SUITE_ARTIFACTS_FOLDER: logs
  script:
    - composer test

Library Tests:
  extends:
    - .job-lib-tests
